version: '3'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - '4000:3000'
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
